# Generated by Django 3.1.2 on 2020-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='unique_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
