# Generated by Django 3.1.2 on 2020-10-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0002_shoppinglist_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedlists', to='SmartListApp.user'),
        ),
    ]
