# Generated by Django 3.1.2 on 2020-10-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0004_auto_20201005_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
