# Generated by Django 3.1.2 on 2020-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0005_auto_20201007_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default='old', max_length=45),
            preserve_default=False,
        ),
    ]
