# Generated by Django 3.1.2 on 2021-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0006_user_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='listobject',
            name='ordered_place',
            field=models.IntegerField(default=1),
        ),
    ]
