# Generated by Django 3.1.2 on 2021-06-24 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0007_listobject_ordered_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='listobject',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
