# Generated by Django 3.1.2 on 2021-07-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartListApp', '0008_listobject_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
